version: '3'
services:
  app:
    build: .
    command: npm start
    restart: unless-stopped
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

